import {supabase} from "./supabase.js";import {showToast,statusBadge,priorityBadge,initials,ticketId,escapeHTML,requireUser,setupMenu} from "./utils.js";
let current,providers=[],bookings=[],selectedRating=0;const $=id=>document.getElementById(id);
async function init(){current=await requireUser(supabase,"customer");if(!current)return;setupMenu();$("userName").textContent=current.profile.full_name;$("avatar").textContent=initials(current.profile.full_name);$("greeting").textContent=`Good ${new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}, ${current.profile.full_name.split(" ")[0]} 👋`;$("bookingDate").min=new Date().toISOString().split("T")[0];await loadProviders();await loadBookings();await loadReviews()}
async function loadProviders(){const {data,error}=await supabase.from("providers").select("*").order("rating",{ascending:false});if(error){showToast("Could not load providers");return}providers=data||[]}
$("serviceCategory").onchange=()=>{const cat=$("serviceCategory").value;const list=providers.filter(p=>p.service_category===cat);$("providerSelect").disabled=!cat;$("providerSelect").innerHTML=cat?`<option value="">Choose a professional</option>`+list.map(p=>`<option value="${p.id}">${escapeHTML(p.name)} • ${p.experience} yrs • ${p.rating} ★ • PKR ${Number(p.price).toLocaleString()}</option>`).join(""):`<option value="">Select service first</option>`}
$("bookingForm").onsubmit=async e=>{e.preventDefault();if(!$("bookingForm").checkValidity()){showToast("Please complete all required fields");return}const provider=providers.find(p=>p.id==$("providerSelect").value);if(!provider){showToast("Please select a provider");return}
const ticket=ticketId();const {data,error}=await supabase.from("bookings").insert({ticket_id:ticket,customer_id:current.user.id,provider_id:provider.id,service_category:$("serviceCategory").value,date:$("bookingDate").value,time:$("bookingTime").value,location:$("location").value.trim(),description:$("description").value.trim(),priority:$("priority").value,status:"pending"}).select().single();if(error){showToast(error.message);return}
$("modalTicket").textContent=ticket;$("modalDetails").innerHTML=`<div><strong>Provider:</strong> ${escapeHTML(provider.name)}</div><div><strong>Service:</strong> ${escapeHTML(provider.service_category)}</div><div><strong>Priority:</strong> ${escapeHTML(data.priority)}</div><div><strong>Date:</strong> ${data.date} at ${data.time}</div>`;new bootstrap.Modal("#ticketModal").show();$("bookingForm").reset();$("providerSelect").disabled=true;$("providerSelect").innerHTML="<option>Select service first</option>";await loadBookings()};
async function loadBookings(){const {data,error}=await supabase.from("bookings").select("*, providers(name,location,rating)").eq("customer_id",current.user.id).order("created_at",{ascending:false});if(error){showToast(error.message);return}bookings=data||[];$("totalCount").textContent=bookings.length;$("pendingCount").textContent=bookings.filter(x=>x.status==="pending").length;$("progressCount").textContent=bookings.filter(x=>x.status==="in_progress").length;$("completedCount").textContent=bookings.filter(x=>x.status==="completed").length;renderBookings()}
function renderBookings(){if(!bookings.length){$("requestsList").innerHTML='<div class="request-card text-center py-5"><h5>No requests yet</h5><p class="muted">Your first service request will appear here.</p></div>';return}$("requestsList").innerHTML=bookings.map(b=>{const done=["submitted","accepted","in_progress","completed"];const idx={pending:0,accepted:1,in_progress:2,completed:3,rejected:-1}[b.status];return `<article class="request-card"><div class="request-head"><div><h5>${escapeHTML(b.ticket_id)}</h5><span class="muted">${escapeHTML(b.service_category)} • ${escapeHTML(b.providers?.name||"Provider")}</span></div><div class="d-flex gap-2">${priorityBadge(b.priority)} ${statusBadge(b.status)}</div></div><div class="request-info"><div><strong>Location</strong>${escapeHTML(b.location)}</div><div><strong>Date</strong>${b.date}</div><div><strong>Time</strong>${b.time}</div><div><strong>Provider</strong>${escapeHTML(b.providers?.name||"—")}</div></div><p class="small mb-2">${escapeHTML(b.description)}</p>${b.status!=="rejected"?`<div class="timeline">${done.map((x,i)=>`<div class="timeline-step ${i<=idx?"done":""} ${i===idx?"current":""}">${i===0?"Submitted":x.replace("_"," ").replace(/\\b\\w/g,m=>m.toUpperCase())}</div>`).join("")}</div>`:""}${b.status==="completed"&&!b.reviewed?`<button class="btn btn-primary btn-sm rounded-3 review-btn" data-id="${b.id}">★ Leave a Review</button>`:""}${b.status==="completed"&&b.reviewed?`<span class="small text-success fw-semibold">✓ Review submitted</span>`:""}</article>`}).join("");document.querySelectorAll(".review-btn").forEach(b=>b.onclick=()=>openReview(b.dataset.id))}
async function loadReviews(){const {data}=await supabase.from("reviews").select("*, providers(name)").eq("customer_id",current.user.id).order("created_at",{ascending:false});$("reviewsList").innerHTML=(data||[]).length?(data||[]).map(r=>`<div class="review-box"><div class="d-flex justify-content-between"><strong>${escapeHTML(r.providers?.name||"Provider")}</strong><span class="review-stars">${"★".repeat(r.rating)}${"☆".repeat(5-r.rating)}</span></div><p class="small muted mb-0 mt-2">${escapeHTML(r.review_text)}</p></div>`).join(""):'<div class="review-box muted small">Completed-service reviews will appear here.</div>'}
function openReview(id){selectedRating=0;$("reviewBookingId").value=id;document.querySelectorAll("#starPicker button").forEach(x=>x.classList.remove("selected"));new bootstrap.Modal("#reviewModal").show()}
document.querySelectorAll("#starPicker button").forEach(btn=>btn.onclick=()=>{selectedRating=Number(btn.dataset.star);document.querySelectorAll("#starPicker button").forEach(x=>x.classList.toggle("selected",Number(x.dataset.star)<=selectedRating))});
$("reviewForm").onsubmit=async e=>{e.preventDefault();if(!selectedRating){showToast("Please choose a star rating");return}const id=$("reviewBookingId").value;const {data:b,error:be}=await supabase.from("bookings").select("*").eq("id",id).eq("customer_id",current.user.id).single();if(be||b?.status!=="completed"){showToast("Only completed bookings can be reviewed");return}const {error}=await supabase.from("reviews").insert({booking_id:id,customer_id:current.user.id,provider_id:b.provider_id,rating:selectedRating,review_text:$("reviewText").value.trim()});if(error){showToast(error.message);return}await supabase.from("bookings").update({reviewed:true}).eq("id",id);bootstrap.Modal.getInstance(document.getElementById("reviewModal")).hide();$("reviewForm").reset();showToast("Review submitted — thank you!");await loadBookings();await loadReviews()};
$("refreshBtn").onclick=()=>loadBookings();$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.href="index.html"};init();
